name: "Test"

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello from Job 1
        run: echo "Hello from Job 1!"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello from Job 2
        run: echo "Hello from Job 2!"
