name: "Testing"

on: 
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a Directory
        run: mkdir my_directory

      - name: Create a file
        run: echo "This is a file" > my_directory/test_file.txt

      - name: Display contents of the directory
        run: ls -l my_directory

  job2: 
    runs-on: ubuntu-latest
    needs: job1

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read the content of the file
        run: cat my_directory/test_file.txt

      - name: Append to the file
        run: echo "This is an appended line." >> my_directory/test_file.txt

      - name: Display the updated content of the file
        run: cat my_directory/test_file.txt

      - name: Say hello from Job 2
        run: echo "Hello from Job 2!"
