name: "Testing"

on: 
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Create a Directory
        run: mkdir my_directory

      - name: create a file
        run: echo "This is a file" >my_directory/test_file.txt

      - name: display contetns of the directory
        run : ls -l my_directory

  job2: 
    runs-on: ubuntu-latest
    needs: job1

    steps: 
      - name: checkout code
        uses: actions/checkout@v2

      - name: Read the content of file
        run: cat my_directory/test_file.txt
      - name: append the file
        run: echo "This is an appended line." >> my_directory/test_file.txt

      - name: Display the updated content of file
        run: cat my_directory/test_file.txt

      - name: say hello from job2
        run: echo "hello from job 2"
        
      

        
  
