name: "Test Deployment"

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you wan

      - name: Run tests
        run: npm test # Adjust this command based on your test script

      - name: Say Hello!
        run: echo "Hello there!"
